from ...Cube_Turning.Cube_Turning_CCW import CubeArrayBCCW, CubeArrayDCCW, CubeArrayFCCW, CubeArrayLCCW, CubeArrayRCCW, CubeArrayUCCW
from ...Cube_Turning.Cube_Turning_CW import CubeArrayBCW, CubeArrayDCW, CubeArrayFCW, CubeArrayLCW, CubeArrayRCW, CubeArrayUCW

edge_map = {
    ('BE', 'AE'): CubeArrayUCCW,
    ('BE', 'CE'): CubeArrayUCW,
    ('BE', 'UE'): CubeArrayLCW,
    ('BE', 'OE'): CubeArrayLCCW,
    ('CE', 'BE'): CubeArrayUCCW,
    ('CE', 'DE'): CubeArrayUCW,
    ('CE', 'GE'): CubeArrayBCCW,
    ('CE', 'QE'): CubeArrayBCW,
    ('DE', 'AE'): CubeArrayUCW,
    ('DE', 'CE'): CubeArrayUCCW,
    ('DE', 'WE'): CubeArrayRCCW,
    ('DE', 'ME'): CubeArrayRCW,
    ('EE', 'FE'): CubeArrayRCW,
    ('EE', 'HE'): CubeArrayRCCW,
    ('EE', 'AE'): CubeArrayFCCW,
    ('EE', 'IE'): CubeArrayFCW,
    ('FE', 'EE'): CubeArrayRCCW,
    ('FE', 'GE'): CubeArrayRCW,
    ('FE', 'NE'): CubeArrayUCCW,
    ('FE', 'VE'): CubeArrayUCW,
    ('GE', 'FE'): CubeArrayRCCW,
    ('GE', 'HE'): CubeArrayRCW,
    ('GE', 'CE'): CubeArrayBCW,
    ('GE', 'KE'): CubeArrayBCCW,
    ('HE', 'EE'): CubeArrayRCW,
    ('HE', 'GE'): CubeArrayRCCW,
    ('HE', 'PE'): CubeArrayDCW,
    ('HE', 'XE'): CubeArrayDCCW,
    ('IE', 'JE'): CubeArrayDCW,
    ('IE', 'LE'): CubeArrayDCCW,
    ('IE', 'EE'): CubeArrayFCCW,
    ('IE', 'SE'): CubeArrayFCW,
    ('JE', 'IE'): CubeArrayDCCW,
    ('JE', 'KE'): CubeArrayDCW,
    ('JE', 'WE'): CubeArrayRCW,
    ('JE', 'ME'): CubeArrayRCCW,
    ('KE', 'JE'): CubeArrayDCCW,
    ('KE', 'LE'): CubeArrayDCW,
    ('KE', 'GE'): CubeArrayBCW,
    ('KE', 'QE'): CubeArrayBCCW,
    ('LE', 'IE'): CubeArrayDCW,
    ('LE', 'KE'): CubeArrayDCCW,
    ('LE', 'OE'): CubeArrayLCW,
    ('LE', 'UE'): CubeArrayLCCW,
    ('ME', 'NE'): CubeArrayBCW,
    ('ME', 'PE'): CubeArrayBCCW,
    ('ME', 'DE'): CubeArrayRCCW,
    ('ME', 'JE'): CubeArrayRCW,
    ('NE', 'ME'): CubeArrayBCCW,
    ('NE', 'OE'): CubeArrayBCW,
    ('NE', 'FE'): CubeArrayUCW,
    ('NE', 'RE'): CubeArrayUCCW,
    ('OE', 'NE'): CubeArrayBCCW,
    ('OE', 'PE'): CubeArrayBCW,
    ('OE', 'BE'): CubeArrayLCW,
    ('OE', 'LE'): CubeArrayLCCW,
    ('PE', 'OE'): CubeArrayBCCW,
    ('PE', 'ME'): CubeArrayBCW,
    ('PE', 'HE'): CubeArrayDCCW,
    ('PE', 'TE'): CubeArrayDCW,
    ('QE', 'RE'): CubeArrayLCW,
    ('QE', 'TE'): CubeArrayLCCW,
    ('QE', 'CE'): CubeArrayBCW,
    ('QE', 'KE'): CubeArrayBCCW,
    ('RE', 'QE'): CubeArrayLCCW,
    ('RE', 'SE'): CubeArrayLCW,
    ('RE', 'NE'): CubeArrayUCW,
    ('RE', 'VE'): CubeArrayUCCW,
    ('SE', 'RE'): CubeArrayLCCW,
    ('SE', 'TE'): CubeArrayLCW,
    ('SE', 'AE'): CubeArrayFCW,
    ('SE', 'IE'): CubeArrayFCCW,
    ('TE', 'QE'): CubeArrayLCW,
    ('TE', 'SE'): CubeArrayLCCW,
    ('TE', 'PE'): CubeArrayDCCW,
    ('TE', 'XE'): CubeArrayDCW,
    ('UE', 'VE'): CubeArrayFCW,
    ('UE', 'XE'): CubeArrayFCCW,
    ('UE', 'BE'): CubeArrayLCCW,
    ('UE', 'LE'): CubeArrayLCW,
    ('VE', 'UE'): CubeArrayFCCW,
    ('VE', 'WE'): CubeArrayFCW,
    ('VE', 'FE'): CubeArrayUCCW,
    ('VE', 'RE'): CubeArrayUCW,
    ('WE', 'VE'): CubeArrayFCCW,
    ('WE', 'XE'): CubeArrayFCW,
    ('WE', 'DE'): CubeArrayRCW,
    ('WE', 'JE'): CubeArrayRCCW,
    ('XE', 'UE'): CubeArrayFCW,
    ('XE', 'WE'): CubeArrayFCCW,
    ('XE', 'HE'): CubeArrayDCW,
    ('XE', 'TE'): CubeArrayDCCW,
}

# edge_map = {
#     ('BE', 'AE'): 'move1',
#     ('BE', 'CE'): 'move2',
#     ('BE', 'UE'): 'move3',
#     ('BE', 'OE'): 'move4',
#     ('CE', 'BE'): 'move5',
#     ('CE', 'DE'): 'move6',
#     ('CE', 'GE'): 'move7',
#     ('CE', 'QE'): 'move8',
#     ('DE', 'AE'): 'move9',
#     ('DE', 'CE'): 'move10',
#     ('DE', 'WE'): 'move11',
#     ('DE', 'ME'): 'move12',
#     ('EE', 'FE'): 'move13',
#     ('EE', 'HE'): 'move14',
#     ('EE', 'AE'): 'move15',
#     ('EE', 'IE'): 'move16',
#     ('FE', 'EE'): 'move17',
#     ('FE', 'GE'): 'move18',
#     ('FE', 'NE'): 'move19',
#     ('FE', 'VE'): 'move20',
#     ('GE', 'FE'): 'move21',
#     ('GE', 'HE'): 'move22',
#     ('GE', 'CE'): 'move23',
#     ('GE', 'KE'): 'move24',
#     ('HE', 'EE'): 'move25',
#     ('HE', 'GE'): 'move26',
#     ('HE', 'PE'): 'move27',
#     ('HE', 'XE'): 'move28',
#     ('IE', 'JE'): 'move29',
#     ('IE', 'LE'): 'move30',
#     ('IE', 'EE'): 'move31',
#     ('IE', 'SE'): 'move32',
#     ('JE', 'IE'): 'move33',
#     ('JE', 'KE'): 'move34',
#     ('JE', 'WE'): 'move35',
#     ('JE', 'ME'): 'move36',
#     ('KE', 'JE'): 'move37',
#     ('KE', 'LE'): 'move38',
#     ('KE', 'GE'): 'move39',
#     ('KE', 'QE'): 'move40',
#     ('LE', 'IE'): 'move41',
#     ('LE', 'KE'): 'move42',
#     ('LE', 'OE'): 'move43',
#     ('LE', 'UE'): 'move44',
#     ('ME', 'NE'): 'move45',
#     ('ME', 'PE'): 'move46',
#     ('ME', 'DE'): 'move47',
#     ('ME', 'JE'): 'move48',
#     ('NE', 'ME'): 'move49',
#     ('NE', 'OE'): 'move50',
#     ('NE', 'FE'): 'move51',
#     ('NE', 'RE'): 'move52',
#     ('OE', 'NE'): 'move53',
#     ('OE', 'PE'): 'move54',
#     ('OE', 'BE'): 'move55',
#     ('OE', 'LE'): 'move56',
#     ('PE', 'OE'): 'move57',
#     ('PE', 'ME'): 'move58',
#     ('PE', 'HE'): 'move59',
#     ('PE', 'TE'): 'move60',
#     ('QE', 'RE'): 'move61',
#     ('QE', 'TE'): 'move62',
#     ('QE', 'CE'): 'move63',
#     ('QE', 'KE'): 'move64',
#     ('RE', 'QE'): 'move65',
#     ('RE', 'SE'): 'move66',
#     ('RE', 'NE'): 'move67',
#     ('RE', 'VE'): 'move68',
#     ('SE', 'RE'): 'move69',
#     ('SE', 'TE'): 'move70',
#     ('SE', 'AE'): 'move71',
#     ('SE', 'IE'): 'move72',
#     ('TE', 'QE'): 'move73',
#     ('TE', 'SE'): 'move74',
#     ('TE', 'PE'): 'move75',
#     ('TE', 'XE'): 'move76',
#     ('UE', 'VE'): 'move77',
#     ('UE', 'XE'): 'move78',
#     ('UE', 'BE'): 'move79',
#     ('UE', 'LE'): 'move80',
#     ('VE', 'UE'): 'move81',
#     ('VE', 'WE'): 'move82',
#     ('VE', 'FE'): 'move83',
#     ('VE', 'RE'): 'move84',
#     ('WE', 'VE'): 'move85',
#     ('WE', 'XE'): 'move86',
#     ('WE', 'DE'): 'move87',
#     ('WE', 'JE'): 'move88',
#     ('XE', 'UE'): 'move89',
#     ('XE', 'WE'): 'move90',
#     ('XE', 'HE'): 'move91',
#     ('XE', 'TE'): 'move92',
# }
